#!/bin/bash
#
# Script to create a Docker container for the Eris Linux platform.
#
# This script is used to create container image based on the content of a
# directory containing at least a `Dockerfile` and most of the time
# some source code and build file (such as `Makefile` for instance).
#
# License: MIT
#
# Christophe BLAESS 2026.
#


if [ $# -ne 3 ]
then
	echo "Usage: $0 <architecture> <directory> <container-name>" >&2
	exit 1
fi


# First argument: the target architecture.
# Must be 'arm', 'arm/v7', 'arm/v8', 'arm64'.
#
if [ "${1}" = "arm64" ] || [ "${1}" = "aarch64" ]
then
	buildplatform="arm64"
	fullarch="aarch64-unknown-linux-musl"
elif [ "${1}" = "arm" ] || [ "${1}" = "arm/v7" ]
then
	buildplatform="arm/v7"
	fullarch="armv7-unknown-linux-musleabihf"
elif [ "${1}" = "arm/v8" ]
then
	buildplatform="${1}"
	fullarch="armv8-unknown-linux-musleabihf"
else
	echo "$0: <architecture> must be 'arm' or 'arm64'." >&2
	exit 1
fi


# Second argument: the directory containing the Dockerfile (and all other files) of the container.
#
directory="${2}"
if [ ! -d "${directory}" ] || [ ! -e "${directory}/Dockerfile" ]
then
	echo "$0: <directory> is not a container directory." >&2
	exit 1
fi
previous_directory=$(pwd)
cd "${directory}" || { echo "$0: unable to enter ${directory}" >&2; exit 1; }


# Third argument: the name of the container (not really important for Eris Linux).
#
name="${3}"
if ! echo "${name}" | grep '^[A-Za-z0-9_.+-]\+$' >/dev/null 2>&1
then
	echo "$0: '${name}' is not a valid container name." >&2
	exit 1
fi


# Remove previous Eris Linux container and image.
#
docker container rm -f "eris-linux-container"  2>/dev/null
docker image     rm -f "eris-linux-image"      2>/dev/null
rm -f eris-linux-container.tar eris-linux-container.sha256 eris-linux-container.cmd eris-linux-container+sum.tar.bz2


# Build the image and store it as a tar archive.
#
docker buildx build                        \
    --progress=plain                       \
    --platform linux/"${buildplatform}"    \
    --build-arg FULLARCH="${fullarch}"     \
    --no-cache                             \
    --debug                                \
    --rm                                   \
    -t "eris-linux-image"                  \
    --output type=tar,dest=eris-linux-container.tar . || exit 1


# Extract the "CMD" line of the Dockerfile.
#
sed -ne 's/^.*CMD[[:blank:]]*\[\(.*\)\]$/\1/p' Dockerfile | \
      sed -e 's/"\([^"]*\)",\?[[:blank:]]*/\1 /g' > eris-linux-container.cmd


# Compute the checksum of the image and the command to run.
#
sha256sum eris-linux-container.tar eris-linux-container.cmd > eris-linux-container.sha256


# Gather the container, the command and the checksum in a tar archive.
#
tar -cjf eris-linux-container+sum.tar.bz2  eris-linux-container.tar eris-linux-container.cmd eris-linux-container.sha256 || exit 1


# Move the producted image and erase the temporary files.
#
mv "eris-linux-container+sum.tar.bz2" "${previous_directory}/${name}.tar.bz2"
rm -f eris-linux-container.tar eris-linux-container.sha256 eris-linux-container.cmd eris-linux-container+sum.tar.bz2
cd -

exit 0
